const $=id=>document.getElementById(id);let vocab=[],queue=[],pos=0,correct=0,wrong=[],checked=false;
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[’']/g,"'").replace(/\s+/g,' ').trim();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
function show(a,b){$(a).classList.add('hidden');$(b).classList.remove('hidden')}
async function load(){try{const r=await fetch('daten/band4_unite1.json');const d=await r.json();vocab=d.entries||[];$('setupStatus').textContent=`Band 4 · Unité 1 · ${vocab.length} Vokabeleinträge verfügbar.`}catch(e){$('setupStatus').textContent='Die Vokabeldatei konnte nicht geladen werden.'}}
function makeItem(v,dir){let d=dir==='mixed'?(Math.random()<.5?'de-fr':'fr-de'):dir;return{...v,dir:d,prompt:d==='de-fr'?v.de:v.fr,answer:d==='de-fr'?v.fr:v.de}}
function start(custom){let items;if(custom){items=custom}else{const sec=$('section').value,extra=$('extra').checked;items=vocab.filter(v=>(extra||v.learning_vocabulary)&&(sec==='all'||v.section===sec));items=shuffle(items);const n=$('count').value==='all'?items.length:Number($('count').value);items=items.slice(0,n).map(v=>makeItem(v,$('direction').value))}if(!items.length){$('setupStatus').textContent='Für diese Auswahl wurden keine Vokabeln gefunden.';return}queue=items;pos=0;correct=0;wrong=[];show('setup','practice');render()}
function render(){checked=false;$('practiceAnswer').value='';$('practiceAnswer').disabled=false;$('feedback').className='feedback hidden';$('checkAnswer').classList.remove('hidden');$('nextPractice').classList.add('hidden');const q=queue[pos];$('practiceProgress').textContent=`${pos+1} / ${queue.length}`;$('practiceScore').textContent=`${correct} richtig`;$('practiceBar').style.width=`${pos/queue.length*100}%`;$('practicePrompt').textContent=q.prompt;$('practiceAnswer').focus()}
function check(){if(checked)return;const q=queue[pos],given=$('practiceAnswer').value.trim();if(!given)return;checked=true;const ok=norm(given)===norm(q.answer);if(ok){correct++;$('feedback').className='feedback correct';$('feedback').innerHTML='<strong>Richtig!</strong>'}else{wrong.push({...q,given});$('feedback').className='feedback wrong';$('feedback').innerHTML=`<strong>Noch nicht.</strong><br>Richtige Lösung: <b>${esc(q.answer)}</b>`}$('practiceScore').textContent=`${correct} richtig`;$('practiceAnswer').disabled=true;$('checkAnswer').classList.add('hidden');$('nextPractice').classList.remove('hidden');$('nextPractice').focus()}
function next(){pos++;if(pos>=queue.length)return finish();render()}
function finish(){$('practiceBar').style.width='100%';const pct=Math.round(correct/queue.length*100);$('practicePercent').textContent=pct+' %';$('practiceResultText').textContent=`${correct} von ${queue.length} sicher beantwortet.`;$('practiceMistakes').innerHTML=wrong.length?'<h3>Diese Wörter solltest du wiederholen</h3>'+wrong.map((m,n)=>`<div class="mistake"><b>${n+1}. ${esc(m.prompt)}</b><br>Deine Antwort: <strong>${esc(m.given||'—')}</strong><br>Richtige Lösung: <strong>${esc(m.answer)}</strong></div>`).join(''):'<div class="feedback correct">Super – alles richtig!</div>';$('repeatWrong').classList.toggle('hidden',!wrong.length);show('practice','practiceResult')}
$('startPractice').addEventListener('click',()=>start());$('checkAnswer').addEventListener('click',check);$('nextPractice').addEventListener('click',next);$('practiceAnswer').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();checked?next():check()}});$('repeatWrong').addEventListener('click',()=>{const again=shuffle(wrong.map(m=>({id:m.id,fr:m.fr,de:m.de,dir:m.dir,prompt:m.prompt,answer:m.answer})));show('practiceResult','practice');start(again)});$('newPractice').addEventListener('click',()=>{show('practiceResult','setup')});load();