import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from './supabase-config.js';
const sb=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY),$=id=>document.getElementById(id);let vocab=[],cache=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function shuffle(a){a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function grades(){return[{min:+$('g1p').value,grade:'1+'},{min:+$('g1').value,grade:'1'},{min:+$('g2p').value,grade:'2+'},{min:+$('g2').value,grade:'2'},{min:+$('g3').value,grade:'3'},{min:+$('g4').value,grade:'4'},{min:0,grade:'5'}].sort((a,b)=>b.min-a.min)}
async function init(){const d=await fetch('daten/band4_unite1.json').then(r=>r.json());vocab=d.entries;const secs=[...new Set(vocab.map(e=>e.section))];$('section').innerHTML='<option value="all">Alle Bereiche</option>'+secs.map(x=>`<option>${esc(x)}</option>`).join('');const {data:{session}}=await sb.auth.getSession();toggle(!!session);if(session)refresh()}
function toggle(on){$('loginBox').classList.toggle('hidden',on);$('teacherBox').classList.toggle('hidden',!on)}
$('login').onclick=async()=>{const {error}=await sb.auth.signInWithPassword({email:$('email').value,password:$('password').value});$('loginStatus').textContent=error?error.message:'Angemeldet';if(!error){toggle(true);refresh()}};
$('logout').onclick=async()=>{await sb.auth.signOut();toggle(false)};
$('createTest').onclick=async()=>{const {data:{user}}=await sb.auth.getUser();if(!user)return;const sec=$('section').value,extra=$('extra').checked,dir=$('direction').value;let pool=vocab.filter(e=>(sec==='all'||e.section===sec)&&(extra||e.learning_vocabulary));const cv=$('count').value,n=cv==='all'?pool.length:Math.min(+cv,pool.length);if(!n)return alert('Keine Vokabeln gewählt.');const qs=shuffle(pool).slice(0,n).map((e,i)=>{const d=dir==='mixed'?(Math.random()<.5?'de-fr':'fr-de'):dir;return{id:`q${i+1}`,prompt:d==='de-fr'?e.de:e.fr,answer:d==='de-fr'?e.fr:e.de}});const row={teacher_id:user.id,code:$('code').value.trim().toUpperCase(),title:$('title').value.trim(),class_name:$('className').value.trim(),section:$('section').selectedOptions[0].textContent,direction:dir,question_count:qs.length,include_extra:extra,time_limit_minutes:+$('timeLimit').value||null,grading_scale:grades(),questions:qs};const {error}=await sb.from('tests').insert(row);$('createStatus').textContent=error?error.message:`Test ${row.code} wurde erstellt.`;if(!error)refresh()};
async function refresh(){const {data:tests,error:e1}=await sb.from('tests').select('*').order('created_at',{ascending:false});const {data:results,error:e2}=await sb.from('results').select('*').order('submitted_at',{ascending:false});if(e1||e2){$('dashboard').textContent=(e1||e2).message;return}cache=results||[];$('dashboard').innerHTML=(tests||[]).map(t=>{const rs=cache.filter(r=>r.test_id===t.id);const avg=rs.length?Math.round(rs.reduce((s,r)=>s+r.percent,0)/rs.length):null;return`<div class="test-block"><b>${esc(t.title)}</b> · Code <b>${esc(t.code)}</b> · ${t.time_limit_minutes||'kein'} Min. · ${t.active?'aktiv':'geschlossen'}<br><small>${rs.length} Abgaben${avg!==null?' · Ø '+avg+' %':''}</small>${rs.map(r=>`<div class="history-item">${esc(r.student_name)} (${esc(r.class_name||'')}) — ${r.correct_count}/${r.total_count}, ${r.percent} %, Note ${esc(r.grade)}, ${Math.floor(r.duration_seconds/60)}:${String(r.duration_seconds%60).padStart(2,'0')} Min.</div>`).join('')}</div>`}).join('')||'<p>Noch keine Tests.</p>'}
$('refresh').onclick=refresh;
$('csv').onclick=()=>{let c='Name;Klasse;Punkte;Gesamt;Prozent;Note;Dauer Sekunden;Abgabe\n'+cache.map(r=>[r.student_name,r.class_name,r.correct_count,r.total_count,r.percent,r.grade,r.duration_seconds,r.submitted_at].map(x=>`"${String(x??'').replaceAll('"','""')}"`).join(';')).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+c],{type:'text/csv;charset=utf-8'}));a.download='Franzoesisch_Ergebnisse.csv';a.click()};
init();